### PR TITLE
Remove unnecessary null check in uninitializedFillDefault and make char/wchar check more generic

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by 9il** [comment]
Ping @wilzback, allocator dependency

**Comment by 9il** [comment]
`if (array !is null)` can be just removed. I think memset should be well optimized.  DMD calls it anyway. LDC creates a large unrolled loop.

**Comment by n8sh** [comment]
Wait actually `_memsetFloat` doesn't do anything clever:

https://github.com/dlang/druntime/blob/af10cddb1aa4f652d27533d41be2fb157c47ed0a/src/rt/memset.d#L122-L130
```d
float *_memsetFloat(float *p, float value, size_t count)
{
    float *pstart = p;
    float *ptop;

    for (ptop = &p[count]; p < ptop; p++)
        *p = value;
    return pstart;
}
```

So with optimization enabled this PR is useless even on DMD.

**Comment by n8sh** [comment]
Changed this PR to just removing the unnecessary null check, and change the test for char/wchar to be more generic.

**Comment by 9il** [comment]
Thanks!

**Pull request merged**
